CREATE TABLE tag (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);

CREATE TABLE product (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL,
  price VARCHAR(50) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  stock INT NOT NULL,
  tag_id INT UNSIGNED,
  FOREIGN KEY(tag_id) REFERENCES tag(id)
);

CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  logo_url VARCHAR(255) NOT NULL
);

CREATE TABLE cart (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT UNSIGNED,
  FOREIGN KEY(user_id) REFERENCES user(id)
);

CREATE TABLE cart_product (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  quantity INT NOT NULL,
  cart_id INT UNSIGNED NOT NULL, 
  product_id INT UNSIGNED NOT NULL,
  FOREIGN KEY(cart_id) REFERENCES cart(id),
  FOREIGN KEY(product_id) REFERENCES product(id)
);